### ISSUE TITLE
flow card to set max amp

### ISSUE THREAD

**Issue by kmengvik** [ricott/homey-no.easee#34]
Any possibillity to change this value from the homey app?

![image](https://user-images.githubusercontent.com/16176305/188140276-e328192a-8ba2-49c0-906b-2eec1b15030a.png)

**Comment by dooniem** [comment]
Isn’t this it?
![Uploading 68721056-2820-41E6-9469-C127A046667E.png…]()

**Comment by dooniem** [comment]
Isn’t this it?
![69400DBD-F063-40DF-A9AE-9B139BBD930C](https://user-images.githubusercontent.com/9369839/190341650-5e0b553d-f345-4a60-bb84-2b41e2819b5d.png)

**Comment by kmengvik** [comment]
> Isn’t this it? ![69400DBD-F063-40DF-A9AE-9B139BBD930C](https://user-images.githubusercontent.com/9369839/190341650-5e0b553d-f345-4a60-bb84-2b41e2819b5d.png)

No, with this card you can set any amp. at any time. I use this card to deliver calculated charge current every 2 minutes to the charger. This value can be way high, but with the max setting the carger is limited to that value regardless what the dynamic circuit current is set as. There is no card for that. I do not know if it is possible to set it in the API. Awaiting @ricott to conclude :)

**Comment by dooniem** [comment]
I thought that card more or less changed that exact setting, but with bigger interval?
If the easy app is set to 13A and you set that card to 25A, output is 25. 
But you want to check if the output of that card exceeds a max you have set “somewhere”?  Or am I missing something?

Can’t you use logic and calculate so that card never returns a value higher than a variable you create in Homey you name “max amp”? Then you can use some flow and logic to control that max amp variable outside the 2 minute flow you already have going?

I guess having the developer create a max is easier than creating that logic yourself though 😅

**Comment by kmengvik** [comment]
Good idea, if the card cannot be established, I will try to make a workaround as you suggested 👍

**Comment by ricott** [comment]
Lots of options to change the charge current :)
I add a new action named `Set max charger current`, there is a new [test version](https://homey.app/a/no.easee/test/)
Try it out and see if this is what you were after.

**Comment by ricott** [comment]
Now I found some docs for this setting, sounds like we shouldn't abuse this setting, https://developer.easee.cloud/docs/current-limits-and-control#max-charger-current. 
No comment of using flash to persist the setting but I would guess it is stored in flash on the charger...

**Comment by kmengvik** [comment]
> Lots of options to change the charge current :) I add a new action named `Set max charger current`, there is a new [test version](https://homey.app/a/no.easee/test/) Try it out and see if this is what you were after.

Thank you Richard, perfect! You are the best 👍
