### ISSUE TITLE
Actions to react to charger state changes

### ISSUE THREAD

**Issue by VHamar** [ricott/homey-no.easee#45]
Would like to see the same actions available for charger state as we today have for charger status. 
Today I enable the charger when car comes home and disables it when the car is not at home (charger is mounted outdoors)

- When: Charger state changed
- When: Charger state changed to &lt;state&gt;
- And: Charger state is &lt;state&gt;

**Comment by ricott** [comment]
Hi!

I guess we could add those triggers/conditions. But please be aware it is not recommended to use the enable/disable actions regularly since it writes to local storage (flash) inside your charger. There is a limited number of writes to the lifetime of the flash storage.

Optionally you could use the access setting of the charger. The pad lock to the right inside the Easee mobile app. This will require a known rfid tag or manually trigger start via the Easee app or using the turn on action in a Homey flow. Just plugging in a car won't make the charger start charging. Changing the access also writes to local flash, but the idea is that you only do that once, to restrict access. Then you start a charge session using the above-mentioned ways.

**Comment by VHamar** [comment]
Hi

Then I guess I should retract my request and change my flows to turn on/off instead. Yes I know of the rfid etc, just want to set up an automated disabling of the charger when the car is not at home.
