### ISSUE TITLE
Insights delay for Dynamic circuit current

### ISSUE THREAD

**Issue by kmengvik** [ricott/homey-no.easee#46]
Hi Richard, like I mentioned earlier in the forum, the updating of value for dynamic circuit current in insights is heavily delayed. Today the value was actually changed at 07:31, but was not updated in insights before 08:24. Almost one hour delayed. similar value for charger current is ok, it is just circuit that is way off. Any idea?

**Comment by ricott** [comment]
Yes, it is refreshed much less frequently - on purpose. 
This is because it is fetched using a separate API, and when invoking that API too frequently the Easee cloud API started to throw a 502 HTTP error which in their API means "Rate limit exceeded". This in turn prevented other API calls since they also would become rate limited. To prevent this problem the dynamic circuit current is only refreshed once per hour. 
Potentially we could try to refresh it more frequently today and see what happens. Will test next time I update the app

**Comment by kmengvik** [comment]
Ok, thank you for the update 🫶🏻

**Comment by kmengvik** [comment]
Hi Richard, I can confirm that after the latest test update of the app, that Dynamic Circuit Current is updated in insights instantly. Thank you very much!
