### ISSUE TITLE
Stops working after a short time

### ISSUE THREAD

**Issue by bfisk** [ricott/homey-no.easee#52]
After latest Homey update, the Easee app stops working (values do not update; when trying to push a new value for current, it gives "access token expired".)
Restarting the app fixes the problem temporarily, but it comes back within one or a few hours.

**Comment by Rippledeedoodle** [comment]
i confirm this appears. restarting will create a new token, that expires after a couple of hours.

looked for an option to have a regular call for the token, but couldn't find anything.
![grafik](https://github.com/ricott/homey-no.easee/assets/138689598/df477859-7962-4cb1-a09d-aaad032fb262)
Missing authorization data. Check "Authorization" header

**Comment by ricott** [comment]
We have a dialogue going in the forum thread about this problem.
It started some 9 days ago, ie not related to any Homey Easee app update. Since last release was 17th of May.

The token still claims it is valid for 24h, this I have checked the other day.
Now with the 1.6.6 test version I can see in the logs that the 401 error is across the board, for all API endpoints.

Will have to ask Easee on Slack what is going on, since I have no clue.

**Comment by Rippledeedoodle** [comment]
@ricott seems to be back to normal - did you hear any reasons so far?

**Comment by ricott** [comment]
Sorry, yes I did. Wrote in the forum thread but not here.
Easee had changed the token expiry to 1 hour vs the previous 24 hours.
I must have checked the refresh token instead of the access token when I verified that it was still 24 hours ...
